language: go
go:
  - 1.10.x
install:
  - go get -t github.com/golang/dep/...
  - dep ensure
  - go get -t github.com/mattn/goveralls
  - go get -t golang.org/x/tools/cmd/cover
script:
  - go test task/task_test.go task/task.go
branches:
  only:
    - master
