language: go

go:
  - 1.10
install:
  - go get -u github.com/golang/dep/...
  - dep ensure
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - go test
branches:
  only:
    - master
